// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQwaN1qoDrtVSmZfCaFIpnbJQULNE8fGE',
    appId: '1:1014070151531:web:87a126522f5f66e498a42e',
    messagingSenderId: '1014070151531',
    projectId: 'be-my-valentine-2ec2c',
    authDomain: 'be-my-valentine-2ec2c.firebaseapp.com',
    storageBucket: 'be-my-valentine-2ec2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDMb4LPqtoaGKc7S9CsVE2t3_lpRQboI',
    appId: '1:1014070151531:android:525c457dac41ee2898a42e',
    messagingSenderId: '1014070151531',
    projectId: 'be-my-valentine-2ec2c',
    storageBucket: 'be-my-valentine-2ec2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKUT-qRaRf0c_YRQwJ0bm4xRfytz0usg',
    appId: '1:1014070151531:ios:404fdf744dcad4d698a42e',
    messagingSenderId: '1014070151531',
    projectId: 'be-my-valentine-2ec2c',
    storageBucket: 'be-my-valentine-2ec2c.appspot.com',
    iosBundleId: 'com.example.beMyValentine',
  );
}
